### ISSUE TITLE
Title is not getting saved properly in "Add Title" button.

### ISSUE THREAD

**Issue by jaitensahu** [jaitensahu/Notepad#1]
### Describe the bug:

Issue: On changing name of the note it is not getting saved properly.

### Steps to Reproduce:

1. Open notepad and click on Add Note button (create 3-5 notes)
2. Click on any note and add title 
3. Now without hitting enter click on some other note
4. You can see that the last character is not saved.
5. For example if you added a title "New note" then only "New not" will get saved the last character will clipped off

### Expected behavior:
The whole title should be saved.

**Comment by sundarrr** [comment]
I can work on this. Can you assign it to me?
Thanks

**Comment by Suvansh-7harma** [comment]
Hi @jaitensahu,
I’d love to contribute to this project! Could you please assign this issue to me?

**Comment by jaitensahu** [comment]
Thanks @sundarrr for your interest. The issue is already fixed by @Suvansh-7harma so I have assigned the issue to him. 
And you don't need to wait for assignment just do the change file a PR, if it resolves the issue then your PR will be merged.

If you want to contribute please explore the project and try find out any issue or feature.

**Comment by jaitensahu** [comment]
@Suvansh-7harma for your contribution
