### ISSUE TITLE
[FEATURE] Dark Mode toggle

### ISSUE THREAD

**Issue by sundarrr** [jaitensahu/Notepad#3]
### Describe the feature you want:
I see that there is no dark mode in the website. 

A clear and concise description of the feature you want.
Dark and light mode

### Why is this feature important?
For accessibility and aesthetic look

**Comment by jaitensahu** [comment]
Hi @sundarrr 
I don't see any use case of dark mode here as this app serves the purpose of adding notes I don't think that dark mode is required.
